global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cy-weather-monitor'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  #API Backend metrics
  - job_name: 'fastapi-app'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 5s
